Models/LibraryAsset.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace LibraryManagment.Models
{
    public abstract class LibraryAsset
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        public Status Status { get; set; }
        [Required]
        public decimal Cost { get; set; }
        [Required]
        public int NumberOfCopies { get; set; }
        [DisplayName("Image")]
        public string ImageUrl { get; set; }
        public virtual LibraryBranch Location { get; set; }

    }
}

Controllers/CheckoutsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagment.Data;
using LibraryManagment.Models;
using LibraryManagment.Models.ViewModels;

namespace LibraryManagment.Controllers
{
    public class CheckoutsController : Controller
    {
        private readonly LibraryManagmentContext _context;

        public CheckoutsController(LibraryManagmentContext context)
        {
            _context = context;
        }

        // GET: Checkouts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Checkouts.ToListAsync());
        }

        // GET: Checkouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkout = await _context.Checkouts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (checkout == null)
            {
                return NotFound();
            }

            return View(checkout);
        }

        // GET: Checkouts/Create
        public IActionResult CheckOut(int id)
        {
            var asset = _context.LibraryAssets.FirstOrDefault(m => m.Id == id);
            var model = new CheckoutModels
            {
                AssetId = id,
                ImgUlr = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = IsCheckedOut(id)
            };
            return View(model);
        }

        public IActionResult CheckIn(int assetId)
        {
            CheckInItem(assetId);
            return RedirectToAction("Details", "LibraryAssets", new { id = assetId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId)
        {
            CheckOutItem(assetId, libraryCardId);
            return RedirectToAction("Details","LibraryAssets",new { id = assetId});
        }
        public IActionResult Hold(int assetId)
        {
            var asset = _context.LibraryAssets.FirstOrDefault(m => m.Id == assetId);
            var model = new CheckoutModels
            {
                AssetId = assetId,
                ImgUlr = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = IsCheckedOut(assetId),
                HoldCount = GetCurrentHolds(assetId).Count()
            };
            return View(model);
        }

   

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PlaceHoldItem(int assetId, int libraryCardId)
        {
            PlaceHold(assetId, libraryCardId);
            return RedirectToAction("Details", "LibraryAssets", new { id = assetId });
        }


        public IActionResult MarkLostItem(int assetId)
        {
            MarkLost(assetId);
            return RedirectToAction("Details", "LibraryAssets", new { id = assetId });
        }
        public IActionResult MarkFoundItem(int assetId)
        {
            MarkFound(assetId);
            return RedirectToAction("Details", "LibraryAssets", new { id = assetId });
        }

        // GET: Checkouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkout = await _context.Checkouts.FindAsync(id);
            if (checkout == null)
            {
                return NotFound();
            }
            return View(checkout);
        }

        // POST: Checkouts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Since,Until")] Checkout checkout)
        {
            if (id != checkout.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(checkout);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheckoutExists(checkout.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(checkout);
        }

        // GET: Checkouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkout = await _context.Checkouts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (checkout == null)
            {
                return NotFound();
            }

            return View(checkout);
        }

        // POST: Checkouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var checkout = await _context.Checkouts.FindAsync(id);
            _context.Checkouts.Remove(checkout);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheckoutExists(int id)
        {
            return _context.Checkouts.Any(e => e.Id == id);
        }

        ///////////////////////////////////////
        private bool IsCheckedOut(int assetId)
        {
            return _context.Checkouts.Any(c => c.LibraryAsset.Id == assetId);
        }

        private void MarkLost(int assetId)
        {
            UpdateAssetStatus(assetId, "Lost");
            _context.SaveChanges();
        }
        private void MarkFound(int assetId)
        {
            var now = DateTime.Now;
            UpdateAssetStatus(assetId, "Available");
            RemoveExistingCheckouts(assetId);
            CloseExistingCheckoutHistory(assetId, now);



            _context.SaveChanges();
        }

        private void RemoveExistingCheckouts(int assetId)
        {
            //remove exisiting checkouts
            var checkout = _context.Checkouts.FirstOrDefault(a => a.LibraryAsset.Id == assetId);
            if (checkout != null)
            {
                _context.Remove(checkout);
            }
        }


        private void CloseExistingCheckoutHistory(int assetId, DateTime now)
        {
            // close any existing checkout history
            var history = _context.CheckoutHistories.FirstOrDefault(a => a.LibraryAsset.Id == assetId && a.CheckedIn == null);
            if (history != null)
            {
                _context.Update(history);
                history.CheckedIn = DateTime.Now;
            }
        }

        private void UpdateAssetStatus(int assetId, string status)
        {
            var item = _context.LibraryAssets.FirstOrDefault(a => a.Id == assetId);
            _context.Update(item);
            item.Status = _context.Statuses.FirstOrDefault(s => s.Name == status);
        }

        private void CheckInItem(int assetId)
        {
            var now = DateTime.Now;
            var item = _context.LibraryAssets.FirstOrDefault(a => a.Id == assetId);

            //Remove existing checkout
            RemoveExistingCheckouts(assetId);
            CloseExistingCheckoutHistory(assetId, now);
            var currentHolds = _context.Holds.Where(h => h.LibraryAsset.Id == assetId);
            if (currentHolds.Any())
            {
                CheckOutToEarliesHold(assetId, currentHolds);
                return;
            }
            UpdateAssetStatus(assetId, "Available");
            _context.SaveChanges();
        }

        private void CheckOutToEarliesHold(int assetId, IQueryable<Hold> currentHolds)
        {
            var earliestHold = currentHolds
                .Include(h => h.LibraryAsset)
                .Include(h => h.LibraryCard)
                .OrderBy(h=>h.HoldPlaced).FirstOrDefault();
            var card = earliestHold.LibraryCard;
            _context.Remove(earliestHold);
            _context.SaveChanges();
            CheckOutItem(assetId, card.Id);
        }

        private void CheckOutItem(int assetId, int cardId)
        {
            if (IsCheckedOut(assetId))
            {
                return;
            }
            var now = DateTime.Now;
            var item = _context.LibraryAssets.FirstOrDefault(a => a.Id == assetId);
            UpdateAssetStatus(assetId, "Checked Out");
            var libraryCard = _context.LibraryCards.FirstOrDefault(c => c.Id == cardId);
            var checkout = new Checkout
            {
                LibraryAsset = item,
                LibraryCard = libraryCard,
                Since = now,
                Until = GetDefaultCheckoutTime(now)
            };

            _context.Add(checkout);

            var checkoutHistory = new CheckoutHistory
            {
                CheckedOut = now,
                LibraryAsset = item,
                LibraryCard = libraryCard
            };

            _context.Add(checkoutHistory);
            _context.SaveChanges();
        }

        private DateTime GetDefaultCheckoutTime(DateTime now)
        {
            return now.AddDays(30);
        }

        private void PlaceHold(int assetId, int cardId)
        {
            var now = DateTime.Now;
            var asset = _context.LibraryAssets
                .Include(s=>s.Status)

Views/LibraryAssets/Create.cshtml
@model LibraryManagment.Models.LibraryAsset

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LibraryAsset</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfCopies" class="control-label"></label>
                <input asp-for="NumberOfCopies" class="form-control" />
                <span asp-validation-for="NumberOfCopies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/LibraryAssets/Delete.cshtml
@model LibraryManagment.Models.LibraryAsset

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LibraryAsset</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfCopies)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfCopies)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/LibraryAssets/Details.cshtml
@using LibraryManagment.Models.ViewModels
@model AssetsDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <img src=@Model.ImgUrl alt="@Model.ImgUrl" style="width:40%; height:80%"/>
        </div>
        <div class="col-md-4">
            <p style="font-weight:bold; font-size:2.0rem">@Model.Title</p>
            <p>@Model.AuthorOrDirector</p>
            <p style="font-weight:bold;">@Model.Status</p>
            <p>Type: @Model.Type</p>
            <p>@Model.CurrentLocation</p>
                    @if(Model.Status == "Lost")
        {
            <p>This item has been lost. IT cannot be checked out</p>
            <p><a class="btn btn-sm btn-danger" role="button" asp-controller="" asp-action="" asp-route-id="">Item Found</a></p>
        }
        @if(Model.Status == "Checked Out")
        {
            <p>Checked out by: @Model.PatronName</p>
            <p><a class="btn btn-sm btn-success" role="button" asp-controller="Checkouts" asp-action="CheckIn" asp-route-assetId="@Model.Id">Check in</a></p>
            <p><a class="btn btn-sm btn-warning" role="button" asp-controller="Checkouts" asp-action="Hold" asp-route-assetId="@Model.Id">Place Hold</a></p>
        }
        @if(Model.Status == "Available")
        {
            <p><a class="btn btn-sm btn-info" role="button" asp-controller="Checkouts" asp-action="CheckOut" asp-route-id="@Model.Id">Check out</a></p>
            
        }
        </div>
        <div class="col-md-4">
            <table>
                <tr>
                    <td class="itemLabel">ISBN: </td>
                    <td class="itemValue">@Model.ISBN</td>
                </tr>
                <tr>
                    <td class="itemLabel">Deywey Number:</td>
                    <td class="itemValue">@Model.DeweyCallNumber</td>
                </tr>
                <tr>
                    <td class="itemLabel">Replacement Cost:</td>
                    <td class="itemValue">@Model.Cost</td>
                </tr>
            </table>
        </div>
    </div>
    
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<div class="row">
    <div class="col-lg-6">
        <h4>Checkout History</h4>
        <table class="table table-sm table-hover">
            <thead  class="table-dark">
                <tr>
                    <th scope="col">Date Loaned</th>
                    <th scope="col">Date Returned</th>
                    <th scope="col">Card Id</th>
                </tr>
            </thead>
            <tbody>
                    @foreach(var checkout in @Model.CheckoutHistories)
                    {
                        <tr>
                            <td>@checkout.CheckedOut</td>
                            <td>@checkout.CheckedIn</td>
                            <td>@checkout.LibraryCard.Id</td>
                        </tr>
                    }
                </tbody>
        </table>
    </div>
    <div class="col-lg-6">
        <h4>Current Holds</h4>
        <table class="table">
            <thead class="table-dark table-sm table-hover">
                <tr>
                    <th>Hold Placed</th>
                    <th>Patron</th>
                </tr>
            </thead>
            <tbody>
                    @foreach(var hold in @Model.CurrentHolds)
                    {
                        <tr>
                            <td>@hold.HoldPlaced</td>
                            <td>@hold.PatronName</td>
                        </tr>
                    }
            </tbody>
        </table>
    </div>
</div>

Views/LibraryAssets/Edit.cshtml
@model LibraryManagment.Models.LibraryAsset

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LibraryAsset</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfCopies" class="control-label"></label>
                <input asp-for="NumberOfCopies" class="form-control" />
                <span asp-validation-for="NumberOfCopies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/LibraryAssets/Index.cshtml
@using LibraryManagment.Models.ViewModels
@*@model IEnumerable<LibraryManagment.Models.LibraryAsset>*@
@model IEnumerable<AssetsIndexViewModel>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">@Html.DisplayNameFor(model => model.ImgUrl)</th>
      <th scope="col">@Html.DisplayNameFor(model => model.Title)</th>
      <th scope="col">Author/Director</th>
      <th scope="col">Dewey Call Number</th>
    </tr>
  </thead>
  <tbody>
        @foreach(var item in Model)
        {
                <tr>
                    <td><a asp-action="Details" asp-route-id="@item.Id" ><img src="@item.ImgUrl" class="card-img-top" alt="no image" style="width:25%; height: 30%"></a></td>
                    <td>@item.Title</td>
                    <td>@item.AuthorOrDirector</td>
                    <td>@item.DeweyCallNumber</td>
                </tr>
        }
  </tbody>
</table>